FROM microsoft/dotnet:3.0-sdk AS build-env
WORKDIR /app
 

 
# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out
 
# Build runtime image
FROM microsoft/dotnet:3.0-aspnetcore-runtime
WORKDIR /app
COPY — from=build-env /app/out .
CMD ASPNETCORE_URLS=http://*:$PORT dotnet Pokedex.dll